version: '3'

services:
  postgres:
    image: postgres:alpine
    volumes:
      - "network-api:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  network-api:
    driver: local
